version: "3.8"
services:

  # ##################### #
  # Database - PostgreSQL #
  # ##################### #

  database:
    image: postgres:14.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
